version: 2
updates:
  - package-ecosystem: "docker-compose"
    directories: 
      - "/*"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 20
    commit-message:
      prefix: "core:"
    labels:
      - dependencies
