services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:0.55.2
    ports:
      - "4533:4533"
    restart: always
    environment:
      ND_LOGLEVEL: debug
    env_file:
      - ".env"
      - "../.env.shared"
    networks:
      - npm
    volumes:
      - "./data:/data"
      - "../library/music/:/music:ro"