services:
  lrclib-docker:
    image: ghcr.io/2t0m/lrclib-docker:0.0.4
    container_name: lrclib-docker
    volumes:
      - ../library/music:/app/music
    environment:
      USER_AGENT: "lrclib-docker v0.0.1"
      RUN_ONCE: "False"
      RUN_SCHEDULED: "True"
      CRON_SCHEDULE: "0 * * * *"
      API_SLEEP_TIME: "20"
      FILE_LIMIT: "-1"
      LOG_LEVEL: "DEBUG"
      MAX_PARALLEL: "5"
    restart: no
