services:
  nginx_proxy_manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:2.12.6'
    restart: unless-stopped
    ports:
      - '80:80' 
      - '443:443'
      - '81:81'
    networks:
      - npm
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

networks:
  npm:
    driver: bridge