services:
  nginx_proxy_manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:2.12.3'
    restart: unless-stopped
    network_mode: 'host'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt